name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.3
  email_auth: ^2.0.0
  cloud_firestore: ^5.5.0
  flutter_slidable: ^3.1.1
  image_picker: ^1.1.2
  firebase_storage: ^12.3.6
  provider: ^6.1.2
  carousel_slider: ^5.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/Backgrounds/
    - assets/ads/
